services:
  redis-stack:
    image: redis/redis-stack-server:7.4.0-v8
    container_name: fanclub_redis
    ports:
      - "6379:6379"          # Redis 协议端口
    environment:
      - TZ=Asia/Shanghai
#      - REDIS_ARGS=--requirepass 123456  # 设置 Redis 访问密码
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - fanclub-network

  mariadb:
    image: postgres:17-alpine
    container_name: fanclub-pgsql
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fanclub_dev
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fanclub-network

networks:
  fanclub-network:
    driver: bridge
