# 构建阶段
FROM gradle:9.4.1-jdk25-ubi10 AS builder
WORKDIR /app
COPY .. .

ENV SPRING_DOCKER_COMPOSE_ENABLED=false
# 定义构建参数
ARG APP_VERSION
ARG BUILD_TIME
ARG GIT_BRANCH
ARG GIT_COMMIT_ID
ARG GIT_COMMIT_TIME

# 设置资源目录变量以避免重复
ENV RESOURCES_DIR=fanclub-apiserver/src/main/resources

# 生成 git.properties 文件
RUN mkdir -p ${RESOURCES_DIR} && \
    echo "build.time=${BUILD_TIME}" > ${RESOURCES_DIR}/git.properties && \
    echo "app.version=${APP_VERSION}" >> ${RESOURCES_DIR}/git.properties && \
    echo "git.branch=${GIT_BRANCH}" >> ${RESOURCES_DIR}/git.properties && \
    echo "git.commit.id.abbrev=${GIT_COMMIT_ID}" >> ${RESOURCES_DIR}/git.properties && \
    echo "git.commit.time=${GIT_COMMIT_TIME}" >> ${RESOURCES_DIR}/git.properties

# 分阶段构建依赖缓存
RUN --mount=type=cache,target=/home/gradle/.gradle/caches \
    gradle :fanclub-apiserver:bootJar -x test --no-daemon --parallel

# 提取 JAR 分层
RUN java -Djarmode=tools -jar fanclub-apiserver/build/libs/*.jar extract --layers --destination extracted

# 运行阶段
FROM bellsoft/liberica-openjre-debian:25-cds
WORKDIR /application

ARG APP_VERSION
ARG GIT_COMMIT_ID

LABEL maintainer="lilinhong_coding@foxmail.com" \
      license="Apache-2.0" \
      git_commit_id=${GIT_COMMIT_ID} \
      version=${APP_VERSION} \
      description="A api server."

# 设置禁用 Flyway 的环境变量
ENV SPRING_FLYWAY_ENABLED=false
ENV SPRING_DOCKER_COMPOSE_ENABLED=false
ENV SPRING_APPLICATION_VERSION=${APP_VERSION}

# 创建日志目录
RUN mkdir "logs"

# 复制提取的分层内容
COPY --from=builder /app/extracted/dependencies/ ./
COPY --from=builder /app/extracted/spring-boot-loader/ ./
COPY --from=builder /app/extracted/snapshot-dependencies/ ./
COPY --from=builder /app/extracted/application/ ./

# 执行 AOT 缓存训练
RUN java -XX:AOTCacheOutput=app.aot -Dspring.context.exit=onRefresh -jar application.jar

# 暴露应用端口
EXPOSE 8080

# 启动应用（启用 AOT 缓存）
ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "application.jar", "--server.port=8080"]
