# Docker Compose 环境配置
spring:
  application:
    name: fanclub-vup-docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fanclub_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  flyway:
    enabled: false
    locations: classpath:db/pgsql

  docker:
    compose:
      file: compose.yaml
      enabled: true
      lifecycle-management: ${DOCKER_LIFECYCLE:start_only}
  ai:
    openai:
      base-url: https://ark.cn-beijing.volces.com/api/v3
      api-key: ${ARK_API_KEY}
      chat:
        options:
          # 只有这个模型支持结构化输出
          model: doubao-seed-1-6-251015
        completions-path: /chat/completions
    chat:
      client:
        observations:
          log-completion: true
          log-prompt: true

captcha:
  expire:
    default: 10000
    # 文字点选验证码 过期时间设置大一点
    WORD_IMAGE_CLICK: 60000
  secondary:
    enabled: false
  # 初始化默认模板文件
  init-default-resource: true
  local-cache-enabled: true
  local-cache-size: 20



jimmer:
  language: kotlin
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect

logging:
  level:
    llh: debug
#    org.springframework.ai.chat.client.advisor: debug
#    org.springframework.ai: DEBUG
#    org.springframework.web.client: DEBUG
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Bilibili Live SDK 配置
fanclub:
  web:
    domain: "*"
  bili:
    dyn:
      scheduler:
        liko: https://www.bilibili.com/opus/1159880489834643463
    scraper:
      current-bid: 1111
