spring:
  cache:
    type: redis
  application:
    name: ${FANCLUB_APP_NAME:fanclub-vup}
    version: @project.version@
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fanclub_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  flyway:
    enabled: ${DB_FLYWAY_ENABLED:false}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  docker:
    compose:
      file: compose.yaml
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      lifecycle-management: ${DOCKER_LIFECYCLE:start_only}

jimmer:
  language: kotlin
  show-sql: ${FANCLUB_SHOW_SQL:false}
  pretty-sql: ${FANCLUB_SHOW_SQL:false}
  inline-sql-variables: ${FANCLUB_SHOW_SQL:false}


logging:
  level:
    llh: ${FANCLUB_LOG_LEVEL:INFO}
    org.springframework.web: ${FANCLUB_SPRING_LOG_LEVEL:warn}

springdoc:
  api-docs:
    enabled: ${FANCLUB_SWAGGER_ENABLED:false}
  swagger-ui:
    enabled: ${FANCLUB_SWAGGER_ENABLED:false}
fanclub:
  web:
    domain: http://localhost
  bili:
    scraper:
      current-bid: 1111
